name: teamawesomesozeith
description: "A simple and efficient app built with Flutter to keep track of your local cricket team's player statistics. Easily record and view player performance, including runs, wickets, and other key stats, all in one place."

version: 0.0.3+3

environment:
  sdk: ^3.6.2

dependencies:
  http: ^1.3.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/feature/banner.png
    - assets/players/profile.png
    - assets/players/batsman.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
