name: teamawesomeflutter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  http: ^1.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/feature/banner.png
    - assets/players/profile.png
    - assets/players/batsman.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
